homework/TIY_HomeWork_Tracker/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :locations do
    member do
      put :fresh
      put :picked
      put :rejected
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

homework/TIY_HomeWork_Tracker/app/models/location.rb
class Location < ActiveRecord::Base
  has_many :user_locations
  has_many :users, through: :user_locations

  include Workflow 
  workflow do
    state :fresh do
      event :getting_picked, transitions_to: :picked
      event :rejecting, transitions_to: :rejected
    end
    state :picked do
      event :over_ride, transitions_to: :fresh
    end
    state :rejected do
      event :over_ride, transitions_to: :fresh
    end
  end

end

homework/TIY_HomeWork_Tracker/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  has_many :user_locations
  has_many :locations, through: :user_locations

  def set_default_role
    self.role ||= :user
  end
end

homework/TIY_HomeWork_Tracker/app/models/user_location.rb
class UserLocation < ActiveRecord::Base
  belongs_to :user
  belongs_to :location
end

homework/TIY_HomeWork_Tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :nickname) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :nickname, :current_password) }
  end
end

homework/TIY_HomeWork_Tracker/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user_list = User.where.not(id: current_user)
  end
end

homework/TIY_HomeWork_Tracker/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_location, only: [:show, :edit, :update, :destroy, :fresh, :picked, :rejected]
  before_action :user_list, only: [:index, :show, :new, :edit, :update, :destroy]

  def index
    @locations = Location.all
    respond_to do |format|
      format.js
    end
    # @user_locations = policy_scope(location).where(:location_id => @location.id)
  end

# @users = (current_user.blank? ? User.all : User.find(:all, :conditions => ["id != ?", current_user.id]))
# @users = User.where.not(id: user)

  def show
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.create location_data
    if @location.save == true
      redirect_to locations_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @location.update_attributes location_data
      redirect_to location_path(@location)
    else
      render :edit
    end
  end

  def destroy
    @location.delete
    redirect_to locations_path
  end

  def fresh
    @location_id = Location.find params[:id]
    @location.over_ride!
    # redirect_to locations_path
    # respond_to do |format|
    #   format.js
    # end
  end

  def picked
    @location_id = Location.find params[:id]
    @location.getting_picked!
    redirect_to locations_path
  end

  def rejected
    @location_id = Location.find params[:id]
    @location.rejecting!
    redirect_to locations_path
  end

private

  def user_list
    @user_list = User.where.not(id: current_user)
  end
  
  def find_location
    @location = Location.find params[:id]
  end

  def location_data
    params.require(:location).permit(:name, :address, :workflow_state, user_ids: [])
  end

end
# , :workflow_state

homework/TIY_HomeWork_Tracker/app/helpers/application_helper.rb
module ApplicationHelper
end

homework/TIY_HomeWork_Tracker/app/helpers/home_helper.rb
module HomeHelper
end

homework/TIY_HomeWork_Tracker/app/helpers/locations_helper.rb
module LocationsHelper
end

homework/TIY_HomeWork_Tracker/app/views/home/index.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} Home
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          - if user_signed_in?
            = content_tag(:a, current_user.nickname)
          - else
            = link_to "Log In", new_user_session_path
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Account
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                = link_to "Edit Account", edit_user_registration_path
              %li.divider
              %li
                = link_to "Log Out", destroy_user_session_path, method: :delete
    / /.navbar-collapse
  / /.container-fluid

homework/TIY_HomeWork_Tracker/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title HomeworkTracker
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

homework/TIY_HomeWork_Tracker/app/views/locations/index.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} Home
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          - if user_signed_in?
            = content_tag(:a, current_user.nickname)
          - else
            = link_to "Log In", new_user_session_path
        - if current_user.admin?
          %li
            = link_to "Add Location", new_location_path
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Account
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                = link_to "Edit Account", edit_user_registration_path
              - if current_user.admin?
                %li.divider
                %li
                  - @user_list.each do |user|
                    = user.nickname
                    %br/
              %li.divider
              %li
                = link_to "Log Out", destroy_user_session_path, method: :delete
    / /.navbar-collapse
  / /.container-fluid

%h1 Locations
- @locations.each do |loc|
  %br
  = loc.name
  %strong
    = loc.workflow_state
  %br/
  = loc.address
  %br/
  / = check_box_tag 'user[location_ids][]', loc.id, current_user.locations.include?(loc)
  / %button.btn.btn-success{:type => "submit"} Save
  / %br/
  / %br/
  - if loc.workflow_state == "fresh"
    %button.btn.btn-default{:type => "button", :class => "workflow_change" + "#{loc.id}", :link => picked_location_path(loc)} Save
    %button.btn.btn-default{:type => "button", :class => "workflow_change", :link => rejected_location_path(loc)} Remove
  - if loc.workflow_state == "rejected"
    - if current_user.admin?
      %button.btn.btn-default{:type => "button", :class => "workflow_change", :link => fresh_location_path(loc)} Reset
  - if loc.workflow_state == "picked"
    - if current_user.admin?
      %button.btn.btn-default{:type => "button", :class => "workflow_change", :link => fresh_location_path(loc)} Reset

homework/TIY_HomeWork_Tracker/app/views/locations/index.js.erb
$("ul.patients").append("<%= escape_javascript(render('patients/patient_partial', comp_patient: patient )) %>")

homework/TIY_HomeWork_Tracker/app/views/locations/new.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} Home
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          - if user_signed_in?
            = content_tag(:a, current_user.nickname)
          - else
            = link_to "Log In", new_user_session_path
        - if user_signed_in?
          %li
            = link_to "Locations", locations_path
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Account
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                = link_to "Edit Account", edit_user_registration_path
              - if current_user.admin?
                %li.divider
                %li
                  - @user_list.each do |user|
                    = user.nickname
                    %br/
              %li.divider
              %li
                = link_to "Log Out", destroy_user_session_path, method: :delete
    / /.navbar-collapse
  / /.container-fluid
%h1 Create Location here
= form_for @location do |f|
  = f.label :name, "Location Name"
  = f.text_field :name
  %br/
  = f.label :address, "Enter Address"
  = f.text_field :address
  %br/
  %button.btn.btn-success{:type => "submit"} Create 